### ISSUE TITLE
Limit the battery

### ISSUE THREAD

**Issue by vaqif14** [KerKerO/MSI-Prestige-15-Hackintosh#1]
Thanks for the great work. I want to know is it possible to limit battery charging to 60%?

**Comment by KerKerO** [comment]
> 
> 
> Thanks for the great work. I want to know is it possible to limit battery charging to 60%?

Yes. But you will need windows and creator center.

1. In the creator center (Tools->Battery Master), you need to set the charge threshold.
2. Turn off the laptop completely.
3. Boot into macos.

(if you reset nvram, need to repeat)
