### ISSUE TITLE
Green screen with HDMI

### ISSUE THREAD

**Issue by gemini444** [KerKerO/MSI-Prestige-15-Hackintosh#2]
Hi @KerKerOgh,
You mention that green screen with HDMI. I have the almost same laptop (msi prestige 15 a10sc-019tr, 1080p) and my HDMI is not working either. I can't find any solution green screen yet. Two thunderbolt ports works with type-c to hdmi adapter.
I'm on Catalina 10.15.7 and bootloader is OC 0.6.6
Do you find the solution?
Thanks.

**Comment by KerKerO** [comment]
> 
> 
> Hi @KerKerOgh,
> You mention that green screen with HDMI. I have the almost same laptop (msi prestige 15 a10sc-019tr, 1080p) and my HDMI is not working either. I can't find any solution green screen yet. Two thunderbolt ports works with type-c to hdmi adapter.
> I'm on Catalina 10.15.7 and bootloader is OC 0.6.6
> Do you find the solution?
> Thanks.

I haven't found a solution yet, the connector patches didn't help.

**Comment by gemini444** [comment]
Thanks for your efforts.

**Comment by vomesk** [comment]
Same for me, i've found it works after sleep/wake up and also with AppleALC.kext disabled but for first boot Ii've tried many patches and configs without results.
