### ISSUE TITLE
Solved bug 2

### ISSUE THREAD

**Issue by vomesk** [KerKerO/MSI-Prestige-15-Hackintosh#3]
Add or change:
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > AAPL,ig-platform-id = 0400A53E
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > device-id = A53E0000
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-enable = 01000000
Device Properties > PciRoot(0x0)/Pci(0x2,0x0) > framebuffer-con0-flags = 98000000

Add in boot-args: -igfxblr agdpmod=vit9696

**Comment by KerKerO** [comment]
Thank you so much for your work. Running on smbios 15.4. 
I will test the work of the graphics system and later add the fix to the repository.

**Comment by vomesk** [comment]
I'm running 16,3
