### ISSUE TITLE
[Question] Thunderbolt 3 + External Monitor

### ISSUE THREAD

**Issue by jamesst20** [KerKerO/MSI-Prestige-15-Hackintosh#4]
Hi,

I would like to confirm that the Thunderbolt 3 port is working and also that external monitor from it works.

The guide says 'Type-C to USB Adapter' but I am scared it uses the wavkink technlogy instead.

Thanks
James

**Comment by gemini444** [comment]
Hi @jamesst20,
I have (https://www.caldigit.com/usb-c-pro-dock/ ) TB3 dock with 2 DP port. I just tried and when i connected to my Samsung tv via dp to hdmi cable, laptop screen just blinking. 
Also i have a tb3 enclosure (https://www.amazon.com/ORICO-Transparent-Enclosure-Tool-Free-Samsung970/dp/B07QVBZZTR) works, and hotplug too.

**Comment by jamesst20** [comment]
> Hi @jamesst20,
> I have (https://www.caldigit.com/usb-c-pro-dock/ ) TB3 dock with 2 DP port. I just tried and when i connected to my Samsung tv via dp to hdmi cable, laptop screen just blinking.
> Also i have a tb3 enclosure (https://www.amazon.com/ORICO-Transparent-Enclosure-Tool-Free-Samsung970/dp/B07QVBZZTR) works, and hotplug too.


Thanks for the feedback. So TB3 devices works but not output video?

**Comment by gemini444** [comment]
Yes indeed. Laptop HDMI works oob.

**Comment by jamesst20** [comment]
> Yes indeed. Laptop HDMI works oob.

Thanks for the feedback ! :)
