### ISSUE TITLE
Fan speed values

### ISSUE THREAD

**Issue by gemini444** [KerKerO/MSI-Prestige-15-Hackintosh#5]
Hello there,
First of all, I would like to thank those who contributed to installing hackintosh on this laptop.
I was going to ask do you can see the fan speed values?
Thank you very much.

**Comment by KerKerO** [comment]
> 
> 
> Hello there,
> First of all, I would like to thank those who contributed to installing hackintosh on this laptop.
> I was going to ask do you can see the fan speed values?
> Thank you very much.

Fan speed sensors in mac os are not defined, I could not start them. In Windows, they are also not displayed, they can only be seen in creator center

**Comment by gemini444** [comment]
Thank you very much for answer. @KerKerOgh .
