### ISSUE TITLE
No audio after rebooting from windows

### ISSUE THREAD

**Issue by vaqif14** [KerKerO/MSI-Prestige-15-Hackintosh#6]
All things work perfectly but only when the first time restart from windows switching to mac sound is missing could you fix pls?

**Comment by KerKerO** [comment]
> All things work perfectly but only when the first time restart from windows switching to mac sound is missing could you fix pls?

I do not know how to fix it. The audio amplifier does not start. To make the sound work, just shut down in windows and boot into the mac OS, do not use a reboot.

**Comment by vaqif14** [comment]
Yes it is working but firstly shutdown windows next switch to mac and shutdown and again switch to windows reboot and switch to mac and it is work :)
